/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.login;

import java.awt.Color;
import com.Interfaz.FramePV;
import javax.swing.SwingUtilities;
/**
 *
 * @author manugr
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        PnlMenuVista = new javax.swing.JPanel();
        PnlAdminCli = new javax.swing.JPanel();
        btnAdminClinicos = new javax.swing.JLabel();
        PnlEncargAreaClin = new javax.swing.JPanel();
        btnEncargados = new javax.swing.JLabel();
        PnlPaciente = new javax.swing.JPanel();
        btnPacientes = new javax.swing.JLabel();
        PnlAreaClinic = new javax.swing.JPanel();
        btnAreaClinic = new javax.swing.JLabel();
        PnlCapturador = new javax.swing.JPanel();
        btnCaputradores = new javax.swing.JLabel();
        PnlCargaAlum = new javax.swing.JPanel();
        btnCargaAlumn = new javax.swing.JLabel();
        PnlTratamientos = new javax.swing.JPanel();
        btnTratamientod = new javax.swing.JLabel();
        CargaArchivos = new javax.swing.JPanel();
        btnCargaFile = new javax.swing.JLabel();
        PnlCerrarS = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1016, 622));
        setPreferredSize(new java.awt.Dimension(1016, 622));

        PnlMenuVista.setBackground(new java.awt.Color(0, 102, 255));
        PnlMenuVista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlAdminCli.setBackground(new java.awt.Color(0, 102, 255));
        PnlAdminCli.setMinimumSize(new java.awt.Dimension(149, 50));
        PnlAdminCli.setPreferredSize(new java.awt.Dimension(149, 50));

        btnAdminClinicos.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnAdminClinicos.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminClinicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.png"))); // NOI18N
        btnAdminClinicos.setText("Administradores Clinicos");
        btnAdminClinicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminClinicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminClinicosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminClinicosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnlAdminCliLayout = new javax.swing.GroupLayout(PnlAdminCli);
        PnlAdminCli.setLayout(PnlAdminCliLayout);
        PnlAdminCliLayout.setHorizontalGroup(
            PnlAdminCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAdminCliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdminClinicos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlAdminCliLayout.setVerticalGroup(
            PnlAdminCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlAdminCliLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdminClinicos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PnlMenuVista.add(PnlAdminCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 50));

        PnlEncargAreaClin.setBackground(new java.awt.Color(0, 102, 255));
        PnlEncargAreaClin.setMinimumSize(new java.awt.Dimension(149, 50));

        btnEncargados.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnEncargados.setForeground(new java.awt.Color(255, 255, 255));
        btnEncargados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/3.png"))); // NOI18N
        btnEncargados.setText("Encargados");
        btnEncargados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncargados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncargadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEncargadosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnlEncargAreaClinLayout = new javax.swing.GroupLayout(PnlEncargAreaClin);
        PnlEncargAreaClin.setLayout(PnlEncargAreaClinLayout);
        PnlEncargAreaClinLayout.setHorizontalGroup(
            PnlEncargAreaClinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlEncargAreaClinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEncargados, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        PnlEncargAreaClinLayout.setVerticalGroup(
            PnlEncargAreaClinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEncargados, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PnlMenuVista.add(PnlEncargAreaClin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, -1));

        PnlPaciente.setBackground(new java.awt.Color(0, 102, 255));
        PnlPaciente.setMinimumSize(new java.awt.Dimension(149, 50));

        btnPacientes.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/4.png"))); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPacientesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnlPacienteLayout = new javax.swing.GroupLayout(PnlPaciente);
        PnlPaciente.setLayout(PnlPacienteLayout);
        PnlPacienteLayout.setHorizontalGroup(
            PnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        PnlPacienteLayout.setVerticalGroup(
            PnlPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PnlMenuVista.add(PnlPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, -1));

        PnlAreaClinic.setBackground(new java.awt.Color(0, 102, 255));
        PnlAreaClinic.setMinimumSize(new java.awt.Dimension(149, 50));

        btnAreaClinic.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnAreaClinic.setForeground(new java.awt.Color(255, 255, 255));
        btnAreaClinic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/5.png"))); // NOI18N
        btnAreaClinic.setText("Areas clinicas");
        btnAreaClinic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAreaClinic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAreaClinicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAreaClinicMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnlAreaClinicLayout = new javax.swing.GroupLayout(PnlAreaClinic);
        PnlAreaClinic.setLayout(PnlAreaClinicLayout);
        PnlAreaClinicLayout.setHorizontalGroup(
            PnlAreaClinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlAreaClinicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAreaClinic, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        PnlAreaClinicLayout.setVerticalGroup(
            PnlAreaClinicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAreaClinic, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PnlMenuVista.add(PnlAreaClinic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 200, -1));

        PnlCapturador.setBackground(new java.awt.Color(0, 102, 255));
        PnlCapturador.setMinimumSize(new java.awt.Dimension(149, 50));

        btnCaputradores.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnCaputradores.setForeground(new java.awt.Color(255, 255, 255));
        btnCaputradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.png"))); // NOI18N
        btnCaputradores.setText("Capturadores");
        btnCaputradores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaputradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCaputradoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCaputradoresMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnlCapturadorLayout = new javax.swing.GroupLayout(PnlCapturador);
        PnlCapturador.setLayout(PnlCapturadorLayout);
        PnlCapturadorLayout.setHorizontalGroup(
            PnlCapturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCapturadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCaputradores, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        PnlCapturadorLayout.setVerticalGroup(
            PnlCapturadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCaputradores, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PnlMenuVista.add(PnlCapturador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 50));

        PnlCargaAlum.setBackground(new java.awt.Color(0, 102, 255));
        PnlCargaAlum.setMinimumSize(new java.awt.Dimension(149, 50));

        btnCargaAlumn.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnCargaAlumn.setForeground(new java.awt.Color(255, 255, 255));
        btnCargaAlumn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/6.png"))); // NOI18N
        btnCargaAlumn.setText("Carga de alumnos");
        btnCargaAlumn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargaAlumn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCargaAlumnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargaAlumnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnlCargaAlumLayout = new javax.swing.GroupLayout(PnlCargaAlum);
        PnlCargaAlum.setLayout(PnlCargaAlumLayout);
        PnlCargaAlumLayout.setHorizontalGroup(
            PnlCargaAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCargaAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargaAlumn, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        PnlCargaAlumLayout.setVerticalGroup(
            PnlCargaAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCargaAlumn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PnlMenuVista.add(PnlCargaAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, 50));

        PnlTratamientos.setBackground(new java.awt.Color(0, 102, 255));
        PnlTratamientos.setMinimumSize(new java.awt.Dimension(149, 50));

        btnTratamientod.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnTratamientod.setForeground(new java.awt.Color(255, 255, 255));
        btnTratamientod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/8.png"))); // NOI18N
        btnTratamientod.setText("Tratamientos");
        btnTratamientod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTratamientod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTratamientodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTratamientodMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnlTratamientosLayout = new javax.swing.GroupLayout(PnlTratamientos);
        PnlTratamientos.setLayout(PnlTratamientosLayout);
        PnlTratamientosLayout.setHorizontalGroup(
            PnlTratamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlTratamientosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTratamientod, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        PnlTratamientosLayout.setVerticalGroup(
            PnlTratamientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTratamientosLayout.createSequentialGroup()
                .addComponent(btnTratamientod, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        PnlMenuVista.add(PnlTratamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 50));

        CargaArchivos.setBackground(new java.awt.Color(0, 102, 255));
        CargaArchivos.setMinimumSize(new java.awt.Dimension(149, 50));

        btnCargaFile.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnCargaFile.setForeground(new java.awt.Color(255, 255, 255));
        btnCargaFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/7.png"))); // NOI18N
        btnCargaFile.setText("Carga de archivos");
        btnCargaFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargaFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCargaFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargaFileMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CargaArchivosLayout = new javax.swing.GroupLayout(CargaArchivos);
        CargaArchivos.setLayout(CargaArchivosLayout);
        CargaArchivosLayout.setHorizontalGroup(
            CargaArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargaArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargaFile, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        CargaArchivosLayout.setVerticalGroup(
            CargaArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCargaFile, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PnlMenuVista.add(CargaArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 200, 50));

        PnlCerrarS.setBackground(new java.awt.Color(0, 102, 255));
        PnlCerrarS.setMinimumSize(new java.awt.Dimension(149, 50));

        btnCerrarSesion.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/9.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PnlCerrarSLayout = new javax.swing.GroupLayout(PnlCerrarS);
        PnlCerrarS.setLayout(PnlCerrarSLayout);
        PnlCerrarSLayout.setHorizontalGroup(
            PnlCerrarSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlCerrarSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        PnlCerrarSLayout.setVerticalGroup(
            PnlCerrarSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PnlMenuVista.add(PnlCerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 200, 50));

        icon.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 18)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 255));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/diente.png"))); // NOI18N
        icon.setText("UnsiSoft+");
        icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PnlMenuVista.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 130, 90));

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(PnlMenuVista, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 850, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlMenuVista, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminClinicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminClinicosMouseEntered
        PnlAdminCli.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnAdminClinicosMouseEntered

    private void btnAdminClinicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminClinicosMouseExited
       PnlAdminCli.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnAdminClinicosMouseExited

    private void btnCaputradoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaputradoresMouseExited
        PnlCapturador.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnCaputradoresMouseExited

    private void btnCaputradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaputradoresMouseEntered
        PnlCapturador.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnCaputradoresMouseEntered

    private void btnEncargadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncargadosMouseEntered
        PnlEncargAreaClin.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnEncargadosMouseEntered

    private void btnEncargadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncargadosMouseExited
        PnlEncargAreaClin.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnEncargadosMouseExited

    private void btnPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacientesMouseExited
        PnlPaciente.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnPacientesMouseExited

    private void btnPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacientesMouseEntered
        PnlPaciente.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnPacientesMouseEntered

    private void btnTratamientodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTratamientodMouseEntered
        PnlTratamientos.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnTratamientodMouseEntered

    private void btnTratamientodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTratamientodMouseExited
       PnlTratamientos.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnTratamientodMouseExited

    private void btnCargaAlumnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargaAlumnMouseEntered
        PnlCargaAlum.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnCargaAlumnMouseEntered

    private void btnCargaAlumnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargaAlumnMouseExited
        PnlCargaAlum.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnCargaAlumnMouseExited

    private void btnCargaFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargaFileMouseEntered
        CargaArchivos.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnCargaFileMouseEntered

    private void btnCargaFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargaFileMouseExited
        CargaArchivos.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnCargaFileMouseExited

    private void btnAreaClinicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAreaClinicMouseEntered
        PnlAreaClinic.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnAreaClinicMouseEntered

    private void btnAreaClinicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAreaClinicMouseExited
        PnlAreaClinic.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnAreaClinicMouseExited

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        PnlCerrarS.setBackground(Color.red);
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        PnlCerrarS.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void btnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMousePressed
        this.removeAll();
        FramePV frame=(FramePV) SwingUtilities.getWindowAncestor(this);
        frame.MostrarL();
 
    }//GEN-LAST:event_btnCerrarSesionMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CargaArchivos;
    private javax.swing.JPanel PnlAdminCli;
    private javax.swing.JPanel PnlAreaClinic;
    private javax.swing.JPanel PnlCapturador;
    private javax.swing.JPanel PnlCargaAlum;
    private javax.swing.JPanel PnlCerrarS;
    private javax.swing.JPanel PnlEncargAreaClin;
    private javax.swing.JPanel PnlMenuVista;
    private javax.swing.JPanel PnlPaciente;
    private javax.swing.JPanel PnlTratamientos;
    private javax.swing.JLabel btnAdminClinicos;
    private javax.swing.JLabel btnAreaClinic;
    private javax.swing.JLabel btnCaputradores;
    private javax.swing.JLabel btnCargaAlumn;
    private javax.swing.JLabel btnCargaFile;
    private javax.swing.JLabel btnCerrarSesion;
    private javax.swing.JLabel btnEncargados;
    private javax.swing.JLabel btnPacientes;
    private javax.swing.JLabel btnTratamientod;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
