package com.login;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author manugr
 */
public class Panelog extends javax.swing.JPanel {

    /**
     * Creates new form Panelog
     */
    public Panelog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAlog = new javax.swing.JPanel();
        lblIconoLog = new javax.swing.JLabel();
        lblsisname = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblpsw = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlbtninisiar = new javax.swing.JPanel();
        lblinisiar = new javax.swing.JLabel();
        pswFiel = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAlog.setBackground(new java.awt.Color(0, 102, 255));

        lblIconoLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoPrincipal.png"))); // NOI18N

        lblsisname.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 36)); // NOI18N
        lblsisname.setForeground(new java.awt.Color(255, 255, 255));
        lblsisname.setText("DentalSoft+");

        javax.swing.GroupLayout PanelAlogLayout = new javax.swing.GroupLayout(PanelAlog);
        PanelAlog.setLayout(PanelAlogLayout);
        PanelAlogLayout.setHorizontalGroup(
            PanelAlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAlogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoLog, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsisname, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        PanelAlogLayout.setVerticalGroup(
            PanelAlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAlogLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(lblsisname, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblIconoLog, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        add(PanelAlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtuser.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(204, 204, 204));
        txtuser.setText("Ingrese el nombre de usuario");
        txtuser.setBorder(null);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 380, 40));

        jLabel1.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 24)); // NOI18N
        jLabel1.setText("INICIAR SESION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        lbluser.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbluser.setText("USUARIO");
        add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 380, -1));

        lblpsw.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblpsw.setText("CONTRASEÑA");
        lblpsw.setToolTipText("");
        add(lblpsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 120, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 380, -1));

        pnlbtninisiar.setBackground(new java.awt.Color(0, 102, 255));
        pnlbtninisiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlbtninisiar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlbtninisiarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnlbtninisiarFocusLost(evt);
            }
        });
        pnlbtninisiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblinisiar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblinisiar.setForeground(new java.awt.Color(255, 255, 255));
        lblinisiar.setText("       INICIAR SESION");
        lblinisiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblinisiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblinisiarMouseExited(evt);
            }
        });
        pnlbtninisiar.add(lblinisiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 150, 40));

        add(pnlbtninisiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 150, 40));

        pswFiel.setForeground(new java.awt.Color(204, 204, 204));
        pswFiel.setText("************");
        pswFiel.setBorder(null);
        pswFiel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswFielMousePressed(evt);
            }
        });
        pswFiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswFielActionPerformed(evt);
            }
        });
        add(pswFiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 380, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void pnlbtninisiarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlbtninisiarFocusGained
        
    }//GEN-LAST:event_pnlbtninisiarFocusGained

    private void pnlbtninisiarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlbtninisiarFocusLost
    
    }//GEN-LAST:event_pnlbtninisiarFocusLost

    private void lblinisiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinisiarMouseEntered
        pnlbtninisiar.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_lblinisiarMouseEntered

    private void lblinisiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinisiarMouseExited
        pnlbtninisiar.setBackground(new Color(0,102,255));
    }//GEN-LAST:event_lblinisiarMouseExited

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        if(txtuser.getText().equals("Ingrese el nombre de usuario")){
        txtuser.setText("");
        txtuser.setForeground(Color.black);
        }
        if(String.valueOf(pswFiel.getPassword()).isEmpty()){
        pswFiel.setText("************");
        pswFiel.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void pswFielMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswFielMousePressed
       if(String.valueOf(pswFiel.getPassword()).startsWith("************")){
           pswFiel.setText("");
           pswFiel.setForeground(Color.black);
       }
          
        
        if(txtuser.getText().isEmpty()){
        txtuser.setText("Ingrese el nombre de usuario");
        txtuser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pswFielMousePressed

    private void pswFielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswFielActionPerformed
        
    }//GEN-LAST:event_pswFielActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIconoLog;
    private javax.swing.JLabel lblinisiar;
    private javax.swing.JLabel lblpsw;
    private javax.swing.JLabel lblsisname;
    private javax.swing.JLabel lbluser;
    private javax.swing.JPanel pnlbtninisiar;
    private javax.swing.JPasswordField pswFiel;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
