/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */ 
package Forms;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author david
 */
public class MainP extends javax.swing.JFrame {
private CardLayout cl;
public CardLayout layoutFrame;
public JPanel panelGeneral;

    private static final String PANEL_ADMIN_CLINICOS = "Panel admins clinicos";
    private static final String PANEL_AREA_CLINICA = "Panel area clinica";
    private static final String PANEL_CAPTURADORES = "Panel capturadores";
    private static final String PANEL_CARGA_ALUMNOS = "Panel carga alumnos";
    private static final String PANEL_CARGA_ARCHIVOS = "Panel carga archivos";
    private static final String PANEL_ENCARGADOS = "Panel encargados";
    private static final String PANEL_PACIENTES = "Panel pacientes";
    private static final String PANEL_TRATAMIENTOS = "Panel tratamientos";

    private panel_admin_clinicos pAdminClinicos;
    private panel_area_clinica pAreaClinica;
    private panel_capturadores pCapturadores;
    private panel_carga_alumnos pCargaAlum;
    private panel_carga_archivos pCargaArchi;
    private panel_encargados pEncargados;
    private panel_pacientes pPacientes;
    private panel_tratamientos pTratamientos;
    private panel_login pLogin;
    
    /**
     * Creates new form MainP
     */
    public MainP() {
        initComponents();
        // AQUI LE DOY EL TAMAÑO Y LA LOCATION AL FRAME
        setSize(1200,800);
        setLocationRelativeTo(null);
        
        //PONGO UN CARDLAYUT PARA UN PANELGENERAL QUE TENDRA TODO
        layoutFrame = new CardLayout();
        panelGeneral=new JPanel(layoutFrame);
        
        
        
        //INSTANCIO P LOGIN
        pLogin = new panel_login(this);
        
       /* METO EL PANEL DE LOS BOTONES Y EL PANEL CONTENT
        AL PANEL BACKGROUND, ES CONO UN PANEL QUE GUARDA TODO LO DEL SISTEMA*/        
        panelBackground.add(panel_buttons, BorderLayout.WEST);
        panelBackground.add(panel_content, BorderLayout.CENTER);
        
        ajustarLabels();
        
       // this.setLayout(new BorderLayout());
        
       // LE PONGO EL CARLAYOUT AL CONTENT
        cl=new CardLayout();
        panel_content.setLayout(cl);
        
        //wa crear instancias xd
        instanciarPaneles();
        addPaneles();
        
        panelGeneral.add(panelBackground,"Todo el contenido");
        panelGeneral.add(pLogin,"Login");
        
        setContentPane(panelGeneral);
        
        
        showLogin();
        //showMainContent();
        
        
        
        //System.out.println(lbl_icono_logo.getText());

        
    }
    private void showPanel(String panelsito){
        cl.show(panel_content,panelsito);
    }
    
    private void instanciarPaneles(){
        pAdminClinicos = new panel_admin_clinicos();
        pAreaClinica = new panel_area_clinica();
        pCapturadores = new panel_capturadores();
        pCargaAlum = new panel_carga_alumnos();
        pCargaArchi = new panel_carga_archivos();
        pEncargados = new panel_encargados();
        pPacientes = new panel_pacientes();
        pTratamientos = new panel_tratamientos();
    }
    
    private void addPaneles(){
        panel_content.add(pAdminClinicos, PANEL_ADMIN_CLINICOS);
        panel_content.add(pAreaClinica, PANEL_AREA_CLINICA);
        panel_content.add(pCapturadores, PANEL_CAPTURADORES);
        panel_content.add(pCargaAlum, PANEL_CARGA_ALUMNOS);
        panel_content.add(pCargaArchi, PANEL_CARGA_ARCHIVOS);
        panel_content.add(pEncargados, PANEL_ENCARGADOS);
        panel_content.add(pPacientes, PANEL_PACIENTES);
        panel_content.add(pTratamientos, PANEL_TRATAMIENTOS);
    }
 
    public void ajustarLabels() {
        Logic_Code.ajustarMedidas(lbl_icono_logo,lbl_admin_clinicos,lbl_areas_clinicas,lbl_capturadores,
                lbl_carga_alumnos,lbl_carga_archivos,lbl_encargados,
                lbl_log_out,lbl_pacientes,lbl_tratamientos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panel_buttons = new javax.swing.JPanel();
        lbl_icono_logo = new javax.swing.JLabel();
        lbl_admin_clinicos = new javax.swing.JLabel();
        lbl_encargados = new javax.swing.JLabel();
        lbl_pacientes = new javax.swing.JLabel();
        lbl_capturadores = new javax.swing.JLabel();
        lbl_tratamientos = new javax.swing.JLabel();
        lbl_carga_alumnos = new javax.swing.JLabel();
        lbl_carga_archivos = new javax.swing.JLabel();
        lbl_areas_clinicas = new javax.swing.JLabel();
        lbl_log_out = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelBackground.setLayout(new java.awt.BorderLayout());

        panel_buttons.setBackground(new java.awt.Color(25, 31, 86));
        panel_buttons.setForeground(new java.awt.Color(86, 95, 200));
        panel_buttons.setPreferredSize(new java.awt.Dimension(200, 800));

        lbl_icono_logo.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 18)); // NOI18N
        lbl_icono_logo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_icono_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/diente.png"))); // NOI18N
        lbl_icono_logo.setText("UnsiSoft+");
        lbl_icono_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_buttons.add(lbl_icono_logo);

        lbl_admin_clinicos.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_admin_clinicos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_admin_clinicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.png"))); // NOI18N
        lbl_admin_clinicos.setText("Admins. Clinicos");
        lbl_admin_clinicos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_admin_clinicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_admin_clinicosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_admin_clinicosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_admin_clinicosMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_admin_clinicos);

        lbl_encargados.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_encargados.setForeground(new java.awt.Color(255, 255, 255));
        lbl_encargados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/3.png"))); // NOI18N
        lbl_encargados.setText("Encargados");
        lbl_encargados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_encargados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_encargadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_encargadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_encargadosMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_encargados);

        lbl_pacientes.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_pacientes.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/4.png"))); // NOI18N
        lbl_pacientes.setText("Pacientes");
        lbl_pacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_pacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_pacientesMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_pacientes);

        lbl_capturadores.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_capturadores.setForeground(new java.awt.Color(255, 255, 255));
        lbl_capturadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.png"))); // NOI18N
        lbl_capturadores.setText("Capturadores");
        lbl_capturadores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_capturadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_capturadoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_capturadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_capturadoresMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_capturadores);

        lbl_tratamientos.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_tratamientos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tratamientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/8.png"))); // NOI18N
        lbl_tratamientos.setText("Tratamientos");
        lbl_tratamientos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_tratamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_tratamientosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_tratamientosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_tratamientosMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_tratamientos);

        lbl_carga_alumnos.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_carga_alumnos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_carga_alumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/6.png"))); // NOI18N
        lbl_carga_alumnos.setText("Carga de alumnos");
        lbl_carga_alumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_carga_alumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_carga_alumnosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_carga_alumnosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_carga_alumnosMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_carga_alumnos);

        lbl_carga_archivos.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_carga_archivos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_carga_archivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/7.png"))); // NOI18N
        lbl_carga_archivos.setText("Carga de archivos");
        lbl_carga_archivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_carga_archivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_carga_archivosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_carga_archivosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_carga_archivosMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_carga_archivos);

        lbl_areas_clinicas.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_areas_clinicas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_areas_clinicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/5.png"))); // NOI18N
        lbl_areas_clinicas.setText("Areas clinicas");
        lbl_areas_clinicas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_areas_clinicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_areas_clinicasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_areas_clinicasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_areas_clinicasMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_areas_clinicas);

        lbl_log_out.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lbl_log_out.setForeground(new java.awt.Color(255, 255, 255));
        lbl_log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/9.png"))); // NOI18N
        lbl_log_out.setText("Cerrar Sesión");
        lbl_log_out.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_log_outMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_log_outMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_log_outMouseExited(evt);
            }
        });
        panel_buttons.add(lbl_log_out);

        panelBackground.add(panel_buttons, java.awt.BorderLayout.LINE_START);

        panel_content.setBackground(new java.awt.Color(255, 255, 255));
        panel_content.setPreferredSize(new java.awt.Dimension(1000, 800));
        panelBackground.add(panel_content, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelBackground, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_admin_clinicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_admin_clinicosMouseClicked
        showPanel(PANEL_ADMIN_CLINICOS);
    }//GEN-LAST:event_lbl_admin_clinicosMouseClicked

    private void lbl_admin_clinicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_admin_clinicosMouseEntered
       Logic_Code.resaltarLabel(lbl_admin_clinicos);
    }//GEN-LAST:event_lbl_admin_clinicosMouseEntered

    private void lbl_admin_clinicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_admin_clinicosMouseExited
       Logic_Code.restaurarLabel(lbl_admin_clinicos);
    }//GEN-LAST:event_lbl_admin_clinicosMouseExited

    private void lbl_encargadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_encargadosMouseClicked
        showPanel(PANEL_ENCARGADOS);
    }//GEN-LAST:event_lbl_encargadosMouseClicked

    private void lbl_encargadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_encargadosMouseEntered
       Logic_Code.resaltarLabel(lbl_encargados);
    }//GEN-LAST:event_lbl_encargadosMouseEntered

    private void lbl_encargadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_encargadosMouseExited
       Logic_Code.restaurarLabel(lbl_encargados);
    }//GEN-LAST:event_lbl_encargadosMouseExited

    private void lbl_pacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pacientesMouseClicked
        showPanel(PANEL_PACIENTES);
    }//GEN-LAST:event_lbl_pacientesMouseClicked

    private void lbl_pacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pacientesMouseEntered
        Logic_Code.resaltarLabel(lbl_pacientes);
    }//GEN-LAST:event_lbl_pacientesMouseEntered

    private void lbl_pacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pacientesMouseExited
        Logic_Code.restaurarLabel(lbl_pacientes);
    }//GEN-LAST:event_lbl_pacientesMouseExited

    private void lbl_capturadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_capturadoresMouseClicked
        showPanel(PANEL_CAPTURADORES);
    }//GEN-LAST:event_lbl_capturadoresMouseClicked

    private void lbl_capturadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_capturadoresMouseEntered
        Logic_Code.resaltarLabel(lbl_capturadores);
    }//GEN-LAST:event_lbl_capturadoresMouseEntered

    private void lbl_capturadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_capturadoresMouseExited
        Logic_Code.restaurarLabel(lbl_capturadores);
    }//GEN-LAST:event_lbl_capturadoresMouseExited

    private void lbl_tratamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tratamientosMouseClicked
        showPanel(PANEL_TRATAMIENTOS);
    }//GEN-LAST:event_lbl_tratamientosMouseClicked

    private void lbl_tratamientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tratamientosMouseEntered
        Logic_Code.resaltarLabel(lbl_tratamientos);
    }//GEN-LAST:event_lbl_tratamientosMouseEntered

    private void lbl_tratamientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tratamientosMouseExited
        Logic_Code.restaurarLabel(lbl_tratamientos);
    }//GEN-LAST:event_lbl_tratamientosMouseExited

    private void lbl_carga_alumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carga_alumnosMouseClicked
        showPanel(PANEL_CARGA_ALUMNOS);
    }//GEN-LAST:event_lbl_carga_alumnosMouseClicked

    private void lbl_carga_alumnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carga_alumnosMouseEntered
        Logic_Code.resaltarLabel(lbl_carga_alumnos);
    }//GEN-LAST:event_lbl_carga_alumnosMouseEntered

    private void lbl_carga_alumnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carga_alumnosMouseExited
        Logic_Code.restaurarLabel(lbl_carga_alumnos);
    }//GEN-LAST:event_lbl_carga_alumnosMouseExited

    private void lbl_carga_archivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carga_archivosMouseClicked
        showPanel(PANEL_CARGA_ARCHIVOS);
    }//GEN-LAST:event_lbl_carga_archivosMouseClicked

    private void lbl_carga_archivosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carga_archivosMouseEntered
        Logic_Code.resaltarLabel(lbl_carga_archivos);
    }//GEN-LAST:event_lbl_carga_archivosMouseEntered

    private void lbl_carga_archivosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_carga_archivosMouseExited
        Logic_Code.restaurarLabel(lbl_carga_archivos);
    }//GEN-LAST:event_lbl_carga_archivosMouseExited

    private void lbl_areas_clinicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_areas_clinicasMouseClicked
        showPanel(PANEL_AREA_CLINICA);
    }//GEN-LAST:event_lbl_areas_clinicasMouseClicked

    private void lbl_areas_clinicasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_areas_clinicasMouseEntered
        Logic_Code.resaltarLabel(lbl_areas_clinicas);
    }//GEN-LAST:event_lbl_areas_clinicasMouseEntered

    private void lbl_areas_clinicasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_areas_clinicasMouseExited
       Logic_Code.restaurarLabel(lbl_areas_clinicas);
    }//GEN-LAST:event_lbl_areas_clinicasMouseExited

    private void lbl_log_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_log_outMouseClicked
       showLogin();
       
    }//GEN-LAST:event_lbl_log_outMouseClicked

    private void lbl_log_outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_log_outMouseEntered
        Logic_Code.resaltarLabel(lbl_log_out);
    }//GEN-LAST:event_lbl_log_outMouseEntered

    private void lbl_log_outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_log_outMouseExited
        Logic_Code.restaurarLabel(lbl_log_out);
    }//GEN-LAST:event_lbl_log_outMouseExited
    
    public void showMainContent() {
    layoutFrame.show(panelGeneral, "Todo el contenido");
    }

    public void showLogin() {
    layoutFrame.show(panelGeneral, "Login");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_admin_clinicos;
    private javax.swing.JLabel lbl_areas_clinicas;
    private javax.swing.JLabel lbl_capturadores;
    private javax.swing.JLabel lbl_carga_alumnos;
    private javax.swing.JLabel lbl_carga_archivos;
    private javax.swing.JLabel lbl_encargados;
    public static javax.swing.JLabel lbl_icono_logo;
    private javax.swing.JLabel lbl_log_out;
    private javax.swing.JLabel lbl_pacientes;
    private javax.swing.JLabel lbl_tratamientos;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panel_buttons;
    private javax.swing.JPanel panel_content;
    // End of variables declaration//GEN-END:variables
}
