/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

/**
 *
 *
 */
public class panel_ventas extends javax.swing.JPanel {

    /**
     * Creates new form panel_admin_clinicos
     */
    public panel_ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblpoductoscobro = new javax.swing.JTable();
        pnlTotal = new javax.swing.JPanel();
        pnlNTotal = new javax.swing.JPanel();
        lbltotaltxt = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        separadorTotal = new javax.swing.JSeparator();
        lblRecibidotxt = new javax.swing.JLabel();
        lblCambiotxt = new javax.swing.JLabel();
        inputRecibido = new javax.swing.JTextField();
        lblinputCambio = new javax.swing.JLabel();
        pnlLector = new javax.swing.JPanel();
        btnCodigo = new javax.swing.JLabel();
        pnlBtnAbrircaja = new javax.swing.JPanel();
        btnPnlAbrir = new javax.swing.JLabel();
        pnlbtnCancelarVenta = new javax.swing.JPanel();
        btnPnlCancelar = new javax.swing.JLabel();
        btnConfirmarVenta = new javax.swing.JPanel();
        lblConfirmarVenta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClienteBusqueda = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        inputClienteCobro = new javax.swing.JTextField();
        lblBuscarClientetxt = new javax.swing.JLabel();
        lblEncargadotxt = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTratamiento = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        pnlTickets = new javax.swing.JPanel();
        btnpnlTickets = new javax.swing.JLabel();
        inputBuscarTrat = new javax.swing.JTextField();
        lblBuscarTratamientos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblpoductoscobro.setBackground(new java.awt.Color(242, 242, 242));
        tblpoductoscobro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idProducto", "Nombre", "Cantidad", "precio"
            }
        ));
        jScrollPane1.setViewportView(tblpoductoscobro);

        pnlNTotal.setBackground(new java.awt.Color(25, 31, 86));

        lbltotaltxt.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lbltotaltxt.setForeground(new java.awt.Color(255, 255, 255));
        lbltotaltxt.setText("Total :");

        lbltotal.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        lbltotal.setForeground(new java.awt.Color(255, 255, 255));
        lbltotal.setText("$0.00");

        javax.swing.GroupLayout pnlNTotalLayout = new javax.swing.GroupLayout(pnlNTotal);
        pnlNTotal.setLayout(pnlNTotalLayout);
        pnlNTotalLayout.setHorizontalGroup(
            pnlNTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNTotalLayout.setVerticalGroup(
            pnlNTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNTotalLayout.createSequentialGroup()
                        .addComponent(lbltotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNTotalLayout.createSequentialGroup()
                        .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        lblRecibidotxt.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lblRecibidotxt.setForeground(new java.awt.Color(153, 153, 153));
        lblRecibidotxt.setText("Recibido  :");

        lblCambiotxt.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblCambiotxt.setForeground(new java.awt.Color(153, 153, 153));
        lblCambiotxt.setText("Cambio  :");

        inputRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRecibidoActionPerformed(evt);
            }
        });

        lblinputCambio.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblinputCambio.setForeground(new java.awt.Color(51, 51, 51));
        lblinputCambio.setText("              $0.00");

        javax.swing.GroupLayout pnlTotalLayout = new javax.swing.GroupLayout(pnlTotal);
        pnlTotal.setLayout(pnlTotalLayout);
        pnlTotalLayout.setHorizontalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(separadorTotal)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblRecibidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblCambiotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblinputCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        pnlTotalLayout.setVerticalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addComponent(pnlNTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRecibidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTotalLayout.createSequentialGroup()
                        .addComponent(inputRecibido)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCambiotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblinputCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        btnCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/escaneo-de-codigo-de-barras.png"))); // NOI18N
        btnCodigo.setText("Lector de codigo");
        btnCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlLectorLayout = new javax.swing.GroupLayout(pnlLector);
        pnlLector.setLayout(pnlLectorLayout);
        pnlLectorLayout.setHorizontalGroup(
            pnlLectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLectorLayout.setVerticalGroup(
            pnlLectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        btnPnlAbrir.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnPnlAbrir.setForeground(new java.awt.Color(0, 0, 153));
        btnPnlAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cajero-automatico.png"))); // NOI18N
        btnPnlAbrir.setText("Abrir Caja");
        btnPnlAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlBtnAbrircajaLayout = new javax.swing.GroupLayout(pnlBtnAbrircaja);
        pnlBtnAbrircaja.setLayout(pnlBtnAbrircajaLayout);
        pnlBtnAbrircajaLayout.setHorizontalGroup(
            pnlBtnAbrircajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPnlAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );
        pnlBtnAbrircajaLayout.setVerticalGroup(
            pnlBtnAbrircajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPnlAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        btnPnlCancelar.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnPnlCancelar.setForeground(new java.awt.Color(255, 0, 0));
        btnPnlCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cerrar.png"))); // NOI18N
        btnPnlCancelar.setText("Cancelar Venta");
        btnPnlCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlbtnCancelarVentaLayout = new javax.swing.GroupLayout(pnlbtnCancelarVenta);
        pnlbtnCancelarVenta.setLayout(pnlbtnCancelarVentaLayout);
        pnlbtnCancelarVentaLayout.setHorizontalGroup(
            pnlbtnCancelarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPnlCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );
        pnlbtnCancelarVentaLayout.setVerticalGroup(
            pnlbtnCancelarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPnlCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        btnConfirmarVenta.setBackground(new java.awt.Color(0, 204, 51));

        lblConfirmarVenta.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        lblConfirmarVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmarVenta.setText("                  Finalizar Venta");
        lblConfirmarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnConfirmarVentaLayout = new javax.swing.GroupLayout(btnConfirmarVenta);
        btnConfirmarVenta.setLayout(btnConfirmarVentaLayout);
        btnConfirmarVentaLayout.setHorizontalGroup(
            btnConfirmarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfirmarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnConfirmarVentaLayout.setVerticalGroup(
            btnConfirmarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfirmarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        tblClienteBusqueda.setBackground(new java.awt.Color(242, 242, 242));
        tblClienteBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane2.setViewportView(tblClienteBusqueda);

        lblBuscarClientetxt.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblBuscarClientetxt.setText("Buscar Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(inputClienteCobro)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBuscarClientetxt)
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarClientetxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(inputClienteCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblEncargadotxt.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblEncargadotxt.setText("Cajero Encargado:  Nombre encargado");

        tblTratamiento.setBackground(new java.awt.Color(242, 242, 242));
        tblTratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "precio", "Seleccionar"
            }
        ));
        jScrollPane3.setViewportView(tblTratamiento);

        btnpnlTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/factura.png"))); // NOI18N
        btnpnlTickets.setText("  Tickets");
        btnpnlTickets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlTicketsLayout = new javax.swing.GroupLayout(pnlTickets);
        pnlTickets.setLayout(pnlTicketsLayout);
        pnlTicketsLayout.setHorizontalGroup(
            pnlTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnpnlTickets, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        pnlTicketsLayout.setVerticalGroup(
            pnlTicketsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnpnlTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblBuscarTratamientos.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        lblBuscarTratamientos.setText("Buscar Tratamiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputBuscarTrat, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBuscarTratamientos))))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pnlbtnCancelarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pnlBtnAbrircaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pnlLector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pnlTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblEncargadotxt)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblBuscarTratamientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputBuscarTrat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlLector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEncargadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlBtnAbrircaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlbtnCancelarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRecibidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRecibidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCodigo;
    private javax.swing.JPanel btnConfirmarVenta;
    private javax.swing.JLabel btnPnlAbrir;
    private javax.swing.JLabel btnPnlCancelar;
    private javax.swing.JLabel btnpnlTickets;
    private javax.swing.JTextField inputBuscarTrat;
    private javax.swing.JTextField inputClienteCobro;
    private javax.swing.JTextField inputRecibido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBuscarClientetxt;
    private javax.swing.JLabel lblBuscarTratamientos;
    private javax.swing.JLabel lblCambiotxt;
    private javax.swing.JLabel lblConfirmarVenta;
    private javax.swing.JLabel lblEncargadotxt;
    private javax.swing.JLabel lblRecibidotxt;
    private javax.swing.JLabel lblinputCambio;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel lbltotaltxt;
    private javax.swing.JPanel pnlBtnAbrircaja;
    private javax.swing.JPanel pnlLector;
    private javax.swing.JPanel pnlNTotal;
    private javax.swing.JPanel pnlTickets;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JPanel pnlbtnCancelarVenta;
    private javax.swing.JSeparator separadorTotal;
    private javax.swing.JTable tblClienteBusqueda;
    private javax.swing.JTable tblTratamiento;
    private javax.swing.JTable tblpoductoscobro;
    // End of variables declaration//GEN-END:variables
}
