/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;



public class panel_pacientes extends javax.swing.JPanel {
    Logic_Code l;
    /**
     * Creates new form panel_pacientes
     */
    public panel_pacientes() {
        initComponents();
        Seleccionado();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblPacientes = new javax.swing.JTable();
        txtBusquedaPnlpacientes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtAPEMpnlpas = new javax.swing.JTextField();
        txtCURPpnlpas = new javax.swing.JTextField();
        txtAPEPpnlpas = new javax.swing.JTextField();
        txtNOMpnlpas = new javax.swing.JTextField();
        txtTELpnlpas = new javax.swing.JTextField();
        lblCURPpnlpas = new javax.swing.JLabel();
        lblAPMpnlpas = new javax.swing.JLabel();
        lblNOMpnlpas = new javax.swing.JLabel();
        lblAPEPpnlpas = new javax.swing.JLabel();
        lblTELpnlpas = new javax.swing.JLabel();
        btnEdicionDP = new javax.swing.JLabel();
        btnDropDato = new javax.swing.JLabel();
        btnInsertarPas = new javax.swing.JLabel();
        btnmodificarPas = new javax.swing.JLabel();
        btnActualizarPastbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbllogo_pas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        TblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CURP", "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(TblPacientes);

        txtBusquedaPnlpacientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaPnlpacientesKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setText("Buscar");

        txtAPEMpnlpas.setEnabled(false);

        txtCURPpnlpas.setEnabled(false);
        txtCURPpnlpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCURPpnlpasActionPerformed(evt);
            }
        });

        txtAPEPpnlpas.setEnabled(false);

        txtNOMpnlpas.setEnabled(false);

        txtTELpnlpas.setEnabled(false);

        lblCURPpnlpas.setText("CURP*");

        lblAPMpnlpas.setText("Apellido Materno*");

        lblNOMpnlpas.setText("Nombre(s)*");

        lblAPEPpnlpas.setText("Apellido Paterno*");

        lblTELpnlpas.setText("Teléfono*");

        btnEdicionDP.setForeground(new java.awt.Color(0, 0, 153));
        btnEdicionDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/boligrafo.png"))); // NOI18N
        btnEdicionDP.setText("Habilitar Edición");
        btnEdicionDP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdicionDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEdicionDPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEdicionDPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEdicionDPMousePressed(evt);
            }
        });

        btnDropDato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/basura.png"))); // NOI18N
        btnDropDato.setText("Eliminar");
        btnDropDato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDropDato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDropDatoMousePressed(evt);
            }
        });

        btnInsertarPas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/0.png"))); // NOI18N
        btnInsertarPas.setText("Ingresar Paciente");
        btnInsertarPas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertarPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInsertarPasMousePressed(evt);
            }
        });

        btnmodificarPas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/boligrafo.png"))); // NOI18N
        btnmodificarPas.setText("Guardar Cambios");
        btnmodificarPas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodificarPas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmodificarPasMousePressed(evt);
            }
        });

        btnActualizarPastbl.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnActualizarPastbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/6.png"))); // NOI18N
        btnActualizarPastbl.setText("Mostrar Clientes");
        btnActualizarPastbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarPastbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarPastblMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(25, 31, 86));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 84));

        lbllogo_pas.setFont(new java.awt.Font("Cantarell", 1, 48)); // NOI18N
        lbllogo_pas.setForeground(new java.awt.Color(255, 255, 255));
        lbllogo_pas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/historial-dental.png"))); // NOI18N
        lbllogo_pas.setText("  Pacientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbllogo_pas)
                .addContainerGap(684, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbllogo_pas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(525, 525, 525)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnActualizarPastbl, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308)
                .addComponent(txtBusquedaPnlpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnEdicionDP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblCURPpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addComponent(lblNOMpnlpas)
                .addGap(232, 232, 232)
                .addComponent(lblAPEPpnlpas))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(txtCURPpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtNOMpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtAPEPpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblAPMpnlpas)
                .addGap(184, 184, 184)
                .addComponent(lblTELpnlpas))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnmodificarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDropDato, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAPEMpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtTELpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarPastbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBusquedaPnlpacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdicionDP)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCURPpnlpas)
                    .addComponent(lblNOMpnlpas)
                    .addComponent(lblAPEPpnlpas))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCURPpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOMpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAPEPpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAPMpnlpas)
                    .addComponent(lblTELpnlpas))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAPEMpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTELpnlpas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodificarPas)
                    .addComponent(btnInsertarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDropDato, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCURPpnlpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCURPpnlpasActionPerformed
        
    }//GEN-LAST:event_txtCURPpnlpasActionPerformed

    private void btnEdicionDPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdicionDPMouseEntered
        btnEdicionDP.setForeground(new Color(25,31,86));
    }//GEN-LAST:event_btnEdicionDPMouseEntered

    private void btnEdicionDPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdicionDPMouseExited
        btnEdicionDP.setForeground(Color.blue);
    }//GEN-LAST:event_btnEdicionDPMouseExited

    private void btnEdicionDPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdicionDPMousePressed
        Logic_Code logic=new Logic_Code();
        logic.habilitar(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas);
    }//GEN-LAST:event_btnEdicionDPMousePressed
    //Insercion a la base de datos 
    private void btnInsertarPasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarPasMousePressed
        validaciones check=new validaciones();
        if(check.campos(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas)==true){
           Logic_Code l=new Logic_Code();
        Cruds s=new Cruds();
        try{
            s.getCon();
            String values="('"+txtCURPpnlpas.getText()+"','"+txtNOMpnlpas.getText()+"','"+txtAPEPpnlpas.getText()+"','"+txtAPEMpnlpas.getText()+"','"+txtTELpnlpas.getText()+"');";
            String sql="INSERT INTO clientes (curp,nombre,apellido_paterno,apellido_materno,telefono) "+"VALUES "+values;
            s.st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Dato agregado con exito");
            l.limpiarT(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas);
            l.deshabilitar(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas);
       }catch(SQLException ex){
           System.out.println(ex.getMessage());
           JOptionPane.showMessageDialog(this, "Tabla no encontrada","Error", JOptionPane.ERROR_MESSAGE);
        } 
        }
        
       
    }//GEN-LAST:event_btnInsertarPasMousePressed
    //modificacion de tratamiento en la base de datos 
    private void btnmodificarPasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmodificarPasMousePressed
    validaciones check=new validaciones();
    Logic_Code l=new Logic_Code();
    if(check.campos(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas)==true){
           
        Cruds s=new Cruds();
        try{
            s.getCon();
            String query="UPDATE clientes SET curp='"+ txtCURPpnlpas.getText()+ "',nombre = '"+txtNOMpnlpas.getText()+"',apellido_paterno= '"+txtAPEPpnlpas.getText()+"',apellido_materno= '"+txtAPEMpnlpas.getText()+"',telefono='"+txtTELpnlpas.getText()+"' WHERE curp='"+txtCURPpnlpas.getText()+"';";
            s.st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Se actualizo el registro", "Exito", JOptionPane.INFORMATION_MESSAGE);
            l.limpiarT(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas);
            l.deshabilitar(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Error al actualizar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnmodificarPasMousePressed
    //borron de datos
    private void btnDropDatoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDropDatoMousePressed
        Logic_Code l=new Logic_Code();
        Cruds s=new Cruds();
    try{
        s.getCon();
        String query="DELETE FROM clientes WHERE curp='"+txtCURPpnlpas.getText()+"';";
       int confirm = JOptionPane.showConfirmDialog(this, "Este dato se borrará permanentemente. ¿Estás segura de querer borrarlo?","Advertencia",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
       if(confirm==JOptionPane.YES_OPTION){
           l.limpiarT(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas);
           l.deshabilitar(txtCURPpnlpas, txtNOMpnlpas, txtAPEPpnlpas, txtAPEMpnlpas, txtTELpnlpas);
           s.st.executeUpdate(query);
           JOptionPane.showMessageDialog(this, "Alumno borrado con exito", "Borrado", JOptionPane.INFORMATION_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(this, "Cancelando operación");
       }
        
        
    }catch(SQLException ex){
        JOptionPane.showMessageDialog(this,"Error al  borrar"+ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_btnDropDatoMousePressed
    // accion de actualizar
    private void btnActualizarPastblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarPastblMousePressed
        Cruds s=new Cruds();
        try{
            s.getCon();
            ResultSet query=s.getSt().executeQuery("SELECT * FROM clientes");
            ArrayList<Pacientes> listaPaciente= new ArrayList<>();
            while(query.next()){
                String CURP=query.getString("curp");
                String nombre=query.getString("nombre");
                String apellidoP=query.getString("apellido_paterno");
                String apellidoM=query.getString("apellido_materno");
                String telefono=query.getString("telefono");
                Pacientes pas=new Pacientes(CURP, nombre, apellidoP, apellidoM, telefono);
                listaPaciente.add(pas);
            }
            TblPacientes.setModel(tablita(listaPaciente));
          query.close();
          s.getCon().close();
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarPastblMousePressed

    private void txtBusquedaPnlpacientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaPnlpacientesKeyReleased
        l=new Logic_Code();
        l.buscarPacienteDinamico(txtBusquedaPnlpacientes.getText(), TblPacientes);
    }//GEN-LAST:event_txtBusquedaPnlpacientesKeyReleased
//Relleno de la tabla 
    public DefaultTableModel tablita(ArrayList<Pacientes> listaPacientes){
        DefaultTableModel m=new DefaultTableModel();
        m.addColumn("Matricula");
        m.addColumn("Nombre");
        m.addColumn("Apellido Paterno");
        m.addColumn("Apellido Materno");
        m.addColumn("Telefono");
        
    
        for(Pacientes a: listaPacientes){
            Object[] fila= new Object[5];
            fila[0]=a.getCurp();
            fila[1]=a.getNombre();
            fila[2]=a.getApellidoPaterno();
            fila[3]=a.getApellidoMaterno();
            fila[4]=a.getTelefono();
            m.addRow(fila);
        
    }
        return m;
}
    //Extrae los datos de la fila seleccionada
    private void Seleccionado() {
        TblPacientes.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                if (!e.getValueIsAdjusting() && TblPacientes.getSelectedRow() != -1) {
                    int selectedRow = TblPacientes.getSelectedRow();
                    try {
                        txtCURPpnlpas.setText(TblPacientes.getValueAt(selectedRow, 0).toString());
                        txtNOMpnlpas.setText(TblPacientes.getValueAt(selectedRow, 1).toString());
                        txtAPEPpnlpas.setText(TblPacientes.getValueAt(selectedRow, 2).toString());
                        txtAPEMpnlpas.setText(TblPacientes.getValueAt(selectedRow, 3).toString());
                        txtTELpnlpas.setText(TblPacientes.getValueAt(selectedRow, 4).toString());

                    } catch (Exception ex) {
                        System.err.println("Error al cargar datos en JTextFields: " + ex.getMessage());
                    }
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblPacientes;
    private javax.swing.JLabel btnActualizarPastbl;
    private javax.swing.JLabel btnDropDato;
    private javax.swing.JLabel btnEdicionDP;
    private javax.swing.JLabel btnInsertarPas;
    private javax.swing.JLabel btnmodificarPas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAPEPpnlpas;
    private javax.swing.JLabel lblAPMpnlpas;
    private javax.swing.JLabel lblCURPpnlpas;
    private javax.swing.JLabel lblNOMpnlpas;
    private javax.swing.JLabel lblTELpnlpas;
    private javax.swing.JLabel lbllogo_pas;
    public javax.swing.JTextField txtAPEMpnlpas;
    public javax.swing.JTextField txtAPEPpnlpas;
    private javax.swing.JTextField txtBusquedaPnlpacientes;
    public javax.swing.JTextField txtCURPpnlpas;
    public javax.swing.JTextField txtNOMpnlpas;
    public javax.swing.JTextField txtTELpnlpas;
    // End of variables declaration//GEN-END:variables
}
