/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Interfaz;
import com.login.Menu;
import com.login.Panelog;
/**
 *
 * @author manugr
 */
public class FramePV extends javax.swing.JFrame {

   
    


    /**
     * Creates new form FramePV
//     */
    public FramePV() {
        initComponents();
        MostrarL();
       
       
    }
    public void MostrarM(){
        
//        FramePV p=new FramePV();
//        p.setVisible(true);
//        Menu m=new Menu();
//        System.out.println("Entre");
//        m.setVisible(true);
        PanelConainer.removeAll();
        PanelConainer.add(new Menu());
        PanelConainer.revalidate();
        PanelConainer.repaint();
    }
   
    public void MostrarL(){
        Panelog log=new Panelog(); 
                
        
        
        PanelConainer.removeAll();
        PanelConainer.add(log);
        PanelConainer.revalidate();
        PanelConainer.repaint();
        
        
        PanelConainer.setVisible(true);
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelConainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1016, 622));

        PanelConainer.setMinimumSize(new java.awt.Dimension(1016, 622));
        PanelConainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(PanelConainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
    
        
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePV().setVisible(true));
        
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelConainer;
    // End of variables declaration//GEN-END:variables
}
